[package]
name = "lumatone-keymap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rust-ini = "0.18.0"
num-traits = "0.2"
num-derive = "0.3"
log = "0.4.0"

lumatone-midi = { path = "../midi" }